const MSG_SCAN = 'MSG_SCAN';
const MSG_SCAN_FINDED = 'MSG_SCAN_FINDED';
const MSG_SCAN_COMPLETE = 'MSG_SCAN_COMPLETE';
const MSG_SAVE_STRATEGY = 'MSG_NEW_STRATEGY';
const MSG_GET_STRATEGY = 'MSG_GET_STRATEGY';
const MSG_DEL_STRATEGY = 'MSG_DEL_STRATEGY';
const MSG_GET_ALL_STRATEGY_BY_STAT = 'MSG_GET_ALL_STRATEGY_BY_STAT';

const MSG_SVAE_SCRIPT = 'MSG_SVAE_SCRIPT';
const MSG_EGT_SCRIPT_BY_STRATEGY = 'MSG_EGT_SCRIPT_BY_STRATEGY';

const MSG_MINIMIZE_WIN = 'MSG_MINIMIZE_WIN';
const MSG_MAXIMIZE_WIN = 'MSG_MAXIMIZE_WIN';
const MSG_WIN_STAT_CHANGE = 'MSG_WIN_STAT_CHANGE';
const MSG_CLOSE_WIN = 'MSG_CLOSE_WIN';

const MSG_ENV_STARTUP = 'MSG_ENV_STARTUP';
const MSG_ENV_SHUTDOWN = 'MSG_ENV_SHUTDOWN';

module.exports = {
    MSG_SCAN,
    MSG_SCAN_FINDED,
    MSG_SCAN_COMPLETE,
    MSG_SAVE_STRATEGY,
    MSG_GET_STRATEGY,
    MSG_DEL_STRATEGY,
    MSG_GET_ALL_STRATEGY_BY_STAT,

    MSG_SVAE_SCRIPT,
    MSG_EGT_SCRIPT_BY_STRATEGY,

    MSG_MINIMIZE_WIN,
    MSG_MAXIMIZE_WIN,
    MSG_WIN_STAT_CHANGE,
    MSG_CLOSE_WIN,
    MSG_ENV_STARTUP,
    MSG_ENV_SHUTDOWN
};